name: TeaReports
version: '1.0'
description: 'Player reporting plugin'
authors: [ 5kuper ]
main: lol.skuper.teareports.TeaReports
api-version: '1.13'

permissions:
  teareports.report:
    description: '/report'
    default: true
  teareports.reports:
    description: '/reports'
    default: false

commands:
  report:
    description: 'Send a report about a player'
    usage: '/<command> <player> <msg>'
    permission: teareports.report
  reports:
    description: 'Moderate reports about players'
    usage: '/<command> check | /<command> answer <id> <msg>'
    permission: teareports.reports